# Generated by Django 5.2.6 on 2025-11-03 15:50

import common.auth_models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('fast-food', 'Fast-food'), ("an'anaviy", "An'anaviy"), ('yengil', 'Yengil taomlar'), ('ichimlik', 'Ichimliklar'), ('shirinlik', 'Shirinliklar'), ('turkish', 'Turkiya Taomlari')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('fio', models.CharField(max_length=56, verbose_name='F.I.O')),
                ('yosh', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', common.auth_models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('skidka', models.SmallIntegerField(default=0, verbose_name='Chegirma(%)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovqat', to='common.category')),
            ],
        ),
        migrations.CreateModel(
            name='OvqatImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal/')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='common.meal')),
            ],
        ),
    ]
