# Generated by Django 5.2.6 on 2025-09-30 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
        migrations.AddField(
            model_name='meal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='skidka',
            field=models.SmallIntegerField(default=0, verbose_name='Chegirma(%)'),
        ),
        migrations.CreateModel(
            name='OvqatImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meal/')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.meal')),
            ],
        ),
    ]
