# Generated by Django 5.2.6 on 2025-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_category_type_alter_meal_ctg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yosh',
            field=models.IntegerField(default=0),
        ),
    ]
