# Generated by Django 5.2.6 on 2025-10-08 00:11

import common.auth_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_yosh'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.auth_models.CustomUserManager()),
            ],
        ),
    ]
